version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintln
        - fmt.Fprintf
        - (io.Closer).Close
        - (*os.File).Close
        - (*net/http.Response).Body.Close
        - os.RemoveAll
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
